import { openDemo, BASE } from './lib.mjs';
import { enableFullPlan, enableSmsAutomation, seedVisitCardVisit } from './seed.mjs';
const out = process.argv[2];
const { browser, ctx, page, studioId } = await openDemo();
enableFullPlan(studioId);
await enableSmsAutomation(page, BASE, studioId);
const visit = seedVisitCardVisit(studioId);
const cfg = await (await page.request.get(`${BASE}/api/v1/sms-campaigns/automation`)).json();
console.log(JSON.stringify(cfg.upsellConsent), JSON.stringify(cfg.visitCardLink));
await page.goto(`${BASE}/visits/${visit}`, { waitUntil: 'networkidle' }); await page.waitForTimeout(2500);
await page.screenshot({ path: `${out}/vc-visit.png` });
await page.getByText('Karta wizyty dla klienta').first().click(); await page.waitForTimeout(2000);
await page.screenshot({ path: `${out}/vc-modal.png` });
const link = await (await page.request.get(`${BASE}/api/visits/${visit}/card-link`)).json();
console.log(JSON.stringify(link));
const phone = await ctx.newPage(); await phone.setViewportSize({ width: 390, height: 844 });
await phone.goto(`${BASE}${link.path}`, { waitUntil: 'networkidle' }); await phone.waitForTimeout(2500);
await phone.screenshot({ path: `${out}/vc-card.png`, fullPage: true });
console.log(studioId, visit);
await browser.close();
